### ISSUE TITLE
tests don't pass on rakudo-moar

### ISSUE THREAD

**Issue by coke** [tadzik/MuEvent#6]
with #4 resolved, get a test failure:

t/01-timed.t .... ok
t/02-idle.t ..... ok
t/03-socket.t ... Socket.poll is NYI on this backend
  in method poll at src/gen/m-CORE.setting:18728
  in sub run-sockets at lib/MuEvent.pm:113
  in sub run-once at lib/MuEvent.pm:130
  in sub run at lib/MuEvent.pm:75
  in block  at t/03-socket.t:115

t/03-socket.t ... Dubious, test returned 1 (wstat 256, 0x100)
Failed 13/13 subtests
t/04-condvar.t .. ok

Test Summary Report
-------------------
t/03-socket.t (Wstat: 256 Tests: 0 Failed: 0)
  Non-zero exit status: 1
  Parse errors: Bad plan.  You planned 13 tests but ran 0.
Files=4, Tests=22, 20 wallclock secs ( 0.04 usr  0.02 sys + 14.09 cusr  0.49 csys = 14.64 CPU)
Result: FAIL
make: *** [test] Error 1

**Comment by tadzik** [comment]
Now it looks like Socket.poll is actually unsupported on all platforms that Rakudo supports. MuEvent's socket mechanisms don't make any sense at this point, and have to be either rethought or ditched completely. I'll open another ticket for that.
